### ISSUE TITLE
Binding Existing Window

### ISSUE THREAD

**Issue by webfolderio** [hasaranga/RFC-Framework#1]
Hello,

Is it possible to connect and existing Window to KWindow.
I am trying to integrate webviewpp with RFC, but cant figure out how to do it.

https://github.com/Soundux/webviewpp

**Comment by hasaranga** [comment]
Hi, sorry for the delay.

You can use **HotPlugInto** method of the KWindow. Pass your webviewpp  window hwnd as the first parameter. Then set the second parameter to true.

**Comment by webfolderio** [comment]
Thanks for the tip, it works as expected.
